// Generated by IcedCoffeeScript 1.8.0-c
var app, bodyParser, cookieParser, express, index, logger, path;

express = require('express');

path = require('path');

logger = require('morgan');

cookieParser = require('cookie-parser');

bodyParser = require('body-parser');

index = require('./routes/index');

app = express();

app.set('views', path.join(__dirname, 'views'));

app.set('view engine', 'jade');

app.use(logger('dev'));

app.use(bodyParser.json());

app.use(bodyParser.urlencoded({
  extended: false
}));

app.use(cookieParser());

app.use(express["static"](path.join(__dirname, 'public')));

app.use('/scripts', express["static"](__dirname + '/node_modules/materialize-css/dist/'));

app.use('/', index);

app.use(function(req, res, next) {
  var err;
  err = new Error('Not Found');
  err.status = 404;
  return next(err);
});

app.use(function(err, req, res, next) {
  var _ref;
  res.locals.message = err.message;
  res.locals.error = (_ref = req.app.get('env') === 'development') != null ? _ref : {
    err: {}
  };
  res.status(err.status || 500);
  return res.render('error');
});

module.exports = app;
