// Generated by IcedCoffeeScript 1.8.0-c
var express, home, router, tool;

express = require('express');

router = express.Router();

home = require('../controllers/home');

tool = require('../controllers/tool');

router.get('/', home.index);

router.get('/tool', tool.index);

router.get('/tool/ips/:ip', tool.get);

router.get('/tool/times/:time', tool.time);

module.exports = router;
