// Generated by IcedCoffeeScript 1.8.0-c
var async, phpjs, utils;

async = require('async');

phpjs = require('phpjs');

utils = require('../lib/utils');

exports.index = function(req, res, next) {
  var data;
  data = {};
  return async.waterfall([
    function(callback) {
      return utils.getIp(function(err, result) {
        if (err) {
          return callback(err);
        }
        data.osIp = result.ip || '';
        callback(null);
      });
    }, function(callback) {
      return utils.getIpByNet('', function(err, result) {
        if (err) {
          return callback(err);
        }
        data.netIp = result.ip || '';
        data.address = result.address || '';
        callback(null);
      });
    }
  ], function(error) {
    if (error) {
      console.log(error);
    }
    return res.render('tool', data);
  });
};

exports.get = function(req, res, next) {
  var ip;
  ip = req.params.ip || '';
  if (!ip) {
    return res.send({
      code: 1,
      msg: 'params error'
    });
  }
  return utils.getIpByNet(ip, function(err, result) {
    return res.send(result);
  });
};

exports.time = function(req, res, next) {
  var intTime;
  intTime = req.params.time || '';
  if (!intTime) {
    return res.send({
      code: 1,
      msg: 'params error'
    });
  }
  return utils.unixTime({
    intTime: intTime
  }, function(err, result) {
    return res.send(result);
  });
};
