// Generated by IcedCoffeeScript 1.8.0-c
var os, phpjs, superagent;

os = require('os');

phpjs = require('phpjs');

superagent = require('superagent');


/*
  通过 Express 的 os 包获取 ip
 */

exports.getIp = function(callback) {
  var data, ifaces, ip;
  callback = callback || function() {};
  ifaces = os.networkInterfaces();
  data = {};
  ip = '';
  Object.keys(ifaces).forEach(function(ifname) {
    return ifaces[ifname].forEach(function(item) {
      if (item.family === 'IPv4' && item.internal === false) {
        return ip = item.address;
      }
    });
  });
  data.ip = ip;
  return callback(null, data);
};


/*
  抓取 ip.cn 的结果获取 ip 信息
 */

exports.getIpByNet = function(ip, callback) {
  var data, ipArrs, url;
  callback = callback || function() {};
  url = ip ? 'http://ip.cn/index.php?ip=' + ip : 'http://ip.cn/';
  data = {};
  ipArrs = '';
  return superagent.get(url).set('User-Agent', 'curl/7.37.1').end(function(err, res) {
    if (err) {
      callback(err);
    }
    ipArrs = res.text.replace(/[\r|\n|来自]/g, '');
    ipArrs = ipArrs ? ipArrs.split('：') : [];
    data.ip = ipArrs[1] ? ipArrs[1] : '';
    data.address = ipArrs[2] ? ipArrs[2] : '';
    return callback(null, data);
  });
};

exports.unixTime = function(info, callback) {
  var data;
  callback = callback || function() {};
  info = info || {};
  data = {};
  if (info.intTime) {
    data.stringTime = phpjs.date("Y-m-d H:i:s", info.intTime);
  }
  if (info.stringTime) {
    data.intTime = phpjs.date(info.stringTime);
  }
  return callback(null, data);
};
